# Generated by Django 5.2 on 2025-05-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_category_options_item_is_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sale_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
