# Generated by Django 5.2 on 2025-05-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_subcategory_alter_item_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Sub Categories'},
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
