# Generated by Django 5.2 on 2025-06-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_category_icon_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
