# Generated by Django 5.2 on 2025-06-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_item_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='main_category',
            new_name='main_category_id',
        ),
    ]
