# Generated by Django 5.2 on 2025-06-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_rename_main_category_subcategory_main_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='sub_category_id',
        ),
    ]
