# Generated by Django 5.2 on 2025-06-13 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_rename_category_item_sub_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex', models.CharField(max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.color'),
        ),
    ]
