# Generated by Django 5.2 on 2025-06-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_color_alter_item_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='name',
            field=models.CharField(default='Red', max_length=50),
        ),
    ]
