# Generated by Django 5.2 on 2025-06-15 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons'),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.color'),
        ),
    ]
